vectorizer__min_df: [0.001, 0.01, 0.1]
vectorizer__max_df: [0.7, 0.8, 0.9, 0.95, 1.0]
vectorizer__ngram_range: [[1, 1], [1, 2]]
umap__n_neighbors: [5, 10, 15]
umap__n_components: [5, 10, 15]
umap__metric: ["cosine"]
hdbscan__min_cluster_size: [2, 3, 5, 10, 15]
hdbscan__min_samples: [1, 5, 10]
bertopic__nr_topics: [2, 5, 10, 25, 50]
bertopic__representation__diversity: [0.0, 0.2, 0.5, 1.0]